admission/adminsite/urls.py
from django.urls import path
from . import views
app_name='adminsite'
urlpatterns=[
    path('history_info', views.history_info, name='history_info'),
    path('history_edit/<int:info_id>', views.history_edit, name='history_edit'),
    path('borderline_predict', views.borderline_predict, name='borderline_predict'),
]

admission/admission/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('information.urls',namespace='information')),
    path('users/',include('users.urls',namespace='users')),
    path('managesite/', include('managesite.urls',namespace='managesite')),
    path('adminsite/', include('adminsite.urls',namespace='adminsite')),
    path('material/', include('material.urls',namespace='material')),
]

admission/information/urls.py
from django.urls import path
from . import views

app_name='informations'

urlpatterns=[
    path('', views.index, name='index'),
    path('admin_index', views.admin_index, name='admin_index'),
    path('stu_menu', views.stu_menu, name='stu_menu'),
    path('new_stu/', views.new_stu, name='new_stu'),
    path('store_success/', views.store_success, name='store_success'),
    path('store_failed/', views.store_failed, name='store_failed'),
    path('exists/<int:info_id>/<int:info_testnum>', views.exists, name='exists'),
    path('search_info/', views.search_info, name='search_info'),
    path('edit_info/<int:info_id>/<int:info_testnum>', views.edit_info, name='edit_info'),
    path('admin_display', views.admin_display, name='admin_display'),
    path('admin_edit/<int:info_id>',views.admin_edit,name='admin_edit'),
    path('output/<int:province_id>',views.output,name='output'),
    path('rank_display/', views.rank_display, name='rank_display'),
    path('delete/<int:info_id>',views.delete, name='delete')
]

admission/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from . import views
app_name='users'

urlpatterns=[
    path('register', views.register, name='register'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout',views.logout_view,name='logout'),
    path('place',views.place,name='place'),
    path('admin_place',views.admin_place,name='admin_place'),
]

admission/adminsite/models.py
from django.db import models
from information.models import MajorInfo
from users.models import UserProfile, Province
# Create your models here.

class HistoryInfo(models.Model):
    major = models.ForeignKey(MajorInfo , on_delete=models.CASCADE,related_name='history_major')
    rank = models.IntegerField(null=True,blank=True)
    province = models.ForeignKey(Province, on_delete=models.CASCADE,related_name='history_province')

class BorderlinePredict(models.Model):
    major = models.ForeignKey(MajorInfo, on_delete=models.CASCADE, related_name='predict_major')
    lowscore = models.IntegerField(null=True, blank=True)
    highscore = models.IntegerField(null=True, blank=True)
    province = models.ForeignKey(Province, on_delete=models.CASCADE, related_name='predict_province')

admission/adminsite/forms.py
from .models import HistoryInfo
from django import forms

class HistoryEditForm(forms.ModelForm):
    class Meta:
        model = HistoryInfo
        fields = ['rank']
        labels = {'rank': '历史录取排名'}

admission/information/forms.py
from django import forms
from .models import StuInfo


class StuInfoForms(forms.ModelForm):
    class Meta:
        model=StuInfo
        fields=['name','testnum','score','rank','tele','high_school','sciorart','major1','major2','major3','application_rank']
        labels={'name':'姓名','testnum':'考号','score':'分数','rank':'排名','tele':'电话','high_school':'毕业中学','sciorart':'文科/理科','major1':'第一意向专业','major2':'第二意向专业（选填）','major3':'第三意向专业（选填）','application_rank':'第几志愿'}


class SearchForms(forms.ModelForm):
    class Meta:
        model = StuInfo
        fields = ['name', 'testnum']
        labels = {'name': '姓名', 'testnum': '考号'}

class AdminEditForms(forms.ModelForm):
    class Meta:
        model=StuInfo
        fields=['name','testnum','score','rank','tele','high_school','sciorart','major1','major2','major3','is_international','application_rank','place','tip']
        labels={'name':'姓名','testnum':'考号','score':'分数','rank':'排名','tele':'电话','high_school':'毕业中学','sciorart':'文科/理科','major1':'第一意向专业','major2':'第二意向专业','major3':'第三意向专业','is_international':'是否报考国际学院','application_rank':'第几志愿','place':'地点','tip':'备注'}
        widgets = {'tip': forms.Textarea(attrs={'cols': 80})}

admission/adminsite/views.py
from django.shortcuts import render
from .models import HistoryInfo,BorderlinePredict
from users.models import UserProfile, Province
from information.models import MajorInfo,RankPredict
from . import models
from .forms import HistoryEditForm
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def admin_only(request):
    if request.user.is_staff is False:
        raise Http404

@login_required
def history_info(request):
    admin_only(request)
    province=UserProfile.objects.get(user=request.user).province
    majors=MajorInfo.objects.all()
    for major in majors:
        try:
            cur = HistoryInfo.objects.get(province=province,major=major)
        except HistoryInfo.DoesNotExist:
            models.HistoryInfo.objects.create(province=province,major=major)
    data = HistoryInfo.objects.filter(province=province)

    context={'datas': data, 'province': province}
    return render(request,'adminsite/history_info.html',context)

@login_required
def history_edit(request,info_id):
    admin_only(request)
    info = HistoryInfo.objects.get(id=info_id)
    if request.method != 'POST':
        form = HistoryEditForm(instance=info)
    else:
        form = HistoryEditForm(instance=info, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminsite:history_info'))

    context = {'info': info, 'form': form}
    return render(request, 'adminsite/history_edit.html', context)

@login_required
def borderline_predict(request):
    admin_only(request)
    provinces = Province.objects.all()
    curprofile = UserProfile.objects.get(user=request.user)
    default = curprofile.province
    if not default:
        default = 1
    province_id = request.GET.get('province', '')
    if not province_id:
        province_id=default
    history=HistoryInfo.objects.filter(province=province_id)
    curdatas=BorderlinePredict.objects.filter(province=province_id)
    for cur in curdatas:
        cur.delete()
    for his in history:
        lowscore=0
        highscore=1000
        if his.rank is None:
            models.BorderlinePredict.objects.create(major=his.major,lowscore=lowscore,highscore=highscore,province=his.province)
            continue
        rules = RankPredict.objects.filter(province=his.province, sciorart=his.major.sciorart).order_by('score')   #升序扫描
        for rule in rules:
            if rule.lowrank is 0:
                continue
            elif rule.lowrank < his.rank:
                break
            lowscore = rule.score
        rules = RankPredict.objects.filter(province=his.province, sciorart=his.major.sciorart).order_by('-score')  # 降序扫描
        for rule in rules:
            if rule.highrank is None:
                continue
            elif rule.highrank > his.rank:
                break
            highscore = rule.score
        models.BorderlinePredict.objects.create(major=his.major, lowscore=lowscore, highscore=highscore, province=his.province)
    data = BorderlinePredict.objects.filter(province=province_id)


    context = {'datas': data, 'dufault': province_id, 'provinces': provinces, 'default': default}
    return render(request, 'adminsite/borderline_predict.html', context)

admission/information/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from django.urls import resolve
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .models import StuInfo,RankPredict
from .forms import StuInfoForms,SearchForms,AdminEditForms
from users.models import UserProfile, Province
from material.models import ConsultMaterial
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import render,HttpResponse
import xlwt
from . import models

from io import StringIO,BytesIO

@login_required
def admin_index(request):
    if request.user.is_superuser is True or request.user.is_staff is True:
        return render(request, 'information/admin_index.html')
    else:
        raise Http404

@login_required
def index(request):
    if request.user.is_superuser is True or request.user.is_staff is True:
        return admin_index(request)
    else:
        user_province_id = UserProfile.objects.get(user=request.user).province.id
        file = ConsultMaterial.objects.filter(province_id__in=[user_province_id, 0])[:2]
        tele = UserProfile.objects.get(user=request.user).telephone
        print(tele)
        context = {'file': file, 'tele':tele, 'name':request.user.first_name}
        return render(request,'information/index.html', context)

def stu_menu(request):
    return render(request,'information/stu_menu.html')

def store_success(request):
    return render(request, 'information/store_success.html')

def store_failed(request):
    return render(request, 'information/store_failed.html')

def exists(request,info_id ,info_testnum):
    context = {'info_id': info_id, 'info_testnum': info_testnum}
    return render(request, 'information/exists.html',context)

def update_predict(new_info):
    try:
        data = RankPredict.objects.get(score=new_info.score,province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        if data.highrank > new_info.rank or data.highrank is 0:
            data.highrank = new_info.rank
        if data.lowrank < new_info.rank or data.lowrank is 0:
            data.lowrank = new_info.rank
    except RankPredict.DoesNotExist:
        models.RankPredict.objects.create(score=new_info.score,province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        data = RankPredict.objects.get(score=new_info.score, province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        data.highrank= new_info.rank
        data.lowrank = new_info.rank
    data.save()
def dupcheck(request,form):
    data = form.cleaned_data
    curnum = data['testnum']
    curname = data['name']
    try:
        dup = StuInfo.objects.get(name=curname, testnum=curnum)
    except StuInfo.DoesNotExist:
        dup = None
    if dup is None:
        new_info=form.save(commit=False)
        cur= request.user
        new_info.staff = cur
        curprofile = UserProfile.objects.get(user=cur)
        new_info.province=curprofile.province
        new_info.place=curprofile.place
        if new_info.major1.is_international is 1:
            new_info.is_international=True
        if new_info.major2:
            if new_info.major2.is_international is 1:
                new_info.is_international=True
        if new_info.major3:
            if new_info.major3.is_international is 1:
                new_info.is_international=True
        update_predict(new_info)
        new_info.save()
        return HttpResponseRedirect(reverse('information:store_success'))
    else:
        return HttpResponseRedirect(reverse('information:exists', kwargs={"info_id":dup.id,"info_testnum":dup.testnum}))

@login_required
def new_stu(request):
    if request.method!='POST':
        form=StuInfoForms()
    else:
        form=StuInfoForms(request.POST)
        if form.is_valid():
            return dupcheck(request,form)

    context={'form':form}
    return render(request, 'information/new_stu.html', context)

@login_required
def search_info(request):
    if request.method!='POST':
        form=SearchForms()
    else:
        form=SearchForms(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            curnum = data['testnum']
            curname = data['name']
            try:
                dup = StuInfo.objects.get(name=curname, testnum=curnum)
            except StuInfo.DoesNotExist:
                dup = None
            if dup is None:
                return HttpResponseRedirect(reverse('information:store_failed'))
            else:
                return HttpResponseRedirect(reverse('information:edit_info', kwargs={"info_id":dup.id,"info_testnum":dup.testnum}))
    context={'form':form}
    return render(request, 'information/search_info.html', context)

@login_required
def edit_info(request,info_id ,info_testnum):
    try:
        info=StuInfo.objects.get(id=info_id,testnum=info_testnum)
    except StuInfo.DoesNotExist:
        raise Http404
    if request.method!='POST':
        form=StuInfoForms(instance=info)
    else:
        form=StuInfoForms(instance=info,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('information:store_success'))

    context = {'info':info,'form': form}
    return render(request, 'information/edit_info.html', context)

def admin_only(request):
    if request.user.is_staff is False:
        raise Http404

@login_required
def admin_display(request):
    admin_only(request)
    data = []
    provinces= Province.objects.all()
    curprofile = UserProfile.objects.get(user=request.user)
    default = curprofile.province
    if not default:
        default = 1
    province_id = request.GET.get('province','')
    if province_id:
        data = StuInfo.objects.filter(province=province_id)
    else:
        data = StuInfo.objects.filter(province=default)
        province_id = default.id

    context={'datas': data,'cur_province':province_id, 'provinces': provinces, 'default': default}
    return render(request,'information/admin_display.html',context)

@login_required
def admin_edit(request,info_id):
    info = StuInfo.objects.get(id=info_id)
    if request.method != 'POST':
        form = AdminEditForms(instance=info)
    else:
        form = AdminEditForms(instance=info, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('information:admin_display'))

    context = {'info': info, 'form': form}
    return render(request, 'information/admin_edit.html', context)


@login_required
def output(request,province_id):
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment;filename=information.xls'
    wb = xlwt.Workbook(encoding = 'utf-8')
    sheet = wb.add_sheet(u'考生信息')
    #1st line
    sheet.write(0,0, '编号')
    sheet.write(0,1, '姓名')
    sheet.write(0,2, '考号')
    sheet.write(0,3, '成绩')
    sheet.write(0,4, '排名')
    sheet.write(0,5, '电话')
    sheet.write(0,6, '毕业高中')
    sheet.write(0,7, '文理科')
    sheet.write(0, 8, '第一意向专业')
    sheet.write(0, 9,'第二意向专业')
    sheet.write(0, 10, '第三意向专业')
    sheet.write(0, 11, '是否填报国际学院')
    sheet.write(0, 12, '第几志愿')
    sheet.write(0, 13, '省份')
    sheet.write(0, 14, '录入教师')
    sheet.write(0, 15, '咨询点')
    sheet.write(0, 16, '备注')
    sheet.write(0, 17, '录入日期')
    sheet.write(0, 18, '录入时间')
    row=1
    for info in StuInfo.objects.filter(province=province_id):
        sheet.write(row, 0, info.id)
        sheet.write(row, 1, info.name)
        sheet.write(row, 2, info.testnum)
        sheet.write(row, 3, info.score)
        sheet.write(row, 4, info.rank)
        sheet.write(row, 5, info.tele)
        sheet.write(row, 6, info.high_school)
        sheet.write(row, 7, str(info.sciorart))
        sheet.write(row, 8, str(info.major1))
        sheet.write(row, 9, str(info.major2))
        sheet.write(row, 10, str(info.major3))
        sheet.write(row, 11, str(info.is_international))
        sheet.write(row, 12, info.application_rank)
        sheet.write(row, 13, str(info.province))
        sheet.write(row, 14, info.staff.first_name)
        sheet.write(row, 15, info.place)
        sheet.write(row, 16, info.tip)
        sheet.write(row, 17, str(info.date))
        sheet.write(row, 18, str(info.time))
        row = row + 1
    output = BytesIO()
    wb.save(output)
    output.seek(0)
    response.write(output.getvalue())
    return response

def rank_display(request):
    admin_only(request)
    provinces= Province.objects.all()
    curprofile = UserProfile.objects.get(user=request.user)
    default = curprofile.province
    province_id = request.GET.get('province','')
    if not province_id:
        province_id=default
    datas=RankPredict.objects.filter(province=province_id)
    for data in datas:
        data.delete()
    datas=StuInfo.objects.filter(province=province_id)
    for data in datas:
        update_predict(data)
    scidata = []
    artdata = []
    if province_id:
        scidata = RankPredict.objects.filter(province=province_id,sciorart=1).order_by('-score')
        artdata = RankPredict.objects.filter(province=province_id, sciorart=2).order_by('-score')
    if len(scidata) > 0:
        cur=scidata[0].score
        for data in scidata:
            while data.score != cur:
                models.RankPredict.objects.create(score=cur,province=data.province,sciorart=data.sciorart,highrank=0,lowrank=0)
                cur=cur-1
            cur=cur-1
    if len(artdata) > 0:
        cur=artdata[0].score
        for data in artdata:
            while data.score is not cur:
                models.RankPredict.objects.create(score=cur,province=data.province,sciorart=data.sciorart,highrank=0,lowrank=0)
                cur = cur - 1
            cur = cur - 1

admission/information/templates/adminsite/borderline_predict.html
<!DOCTYPE HTML>
<html>
  <head>
    <title> 统计信息 </title>
    <meta charset="utf-8">
    <meta name="Generator" content="EditPlus">
    <meta name="Author" content="tschengbin">
    <meta name="Keywords" content="jquery tableSort">
    <meta name="Description" content="">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <style type="text/css">
        p{
            width: 1024px;
            margin: 0 auto;
        }
        table{
            border: solid 1px #666;
            border-collapse: collapse;
            width: 100%;
            cursor: default;
            table-layout: fixed;
        }
        tr{
            border: solid 1px #666;
            height: 30px;
        }
        table thead tr{
            background-color: #ccc;
        }
        td{
            border: solid 1px #666;
            white-space:nowrap;
            overflow:hidden;
            text-overflow: ellipsis;
        }
        th{
            border: solid 1px #666;
            text-align: center;
            cursor: pointer;
        }
        .sequence{
            text-align: center;
        }
    </style>
  </head>

  <h2>录取分数预测</h2>
  <div>生源省份:</div>
  <div class="count">
    <a href="?province={{ default.id }}"><span class="">{{ default.province }}</span></a>
    {% for province in provinces %}
      <a href="?province={{ province.id }}"><span class="">{{ province.province }}</span></a>
    {% endfor %}
  </div>
  <table id="tableSort">
    <thead>
      <tr>
        <th type="number" width="200">专业</th>
        <th type="string" width="140">预测录取线最低分数</th>
        <th type="number" width="140">预测录取线最噶分数</th>
      </tr>
    </thead>
    <tbody>
    {% for data in datas %}
      <tr>
        <td>{{ data.major }}</td>
        <td>{{ data.lowscore }}</td>
        <td>{{ data.highscore }}</td>
        </tr>
    </tbody>
    {% empty %}
      <h2>还未有学生提交</h2>
    {% endfor %}
  </table>
  <div>
    显示0-1000分表示目前搜集的数据不足以进行预测
  </div>
  <div>
    <p><a href="{% url 'information:index' %}">返回首页</a></p>
  </div>
  <script type="text/javascript">
      $(document).ready(function(){
           var tableObject = $('#tableSort');
           var tbHead = tableObject.children('thead');
           var tbHeadTh = tbHead.find('tr th');
           var tbBody = tableObject.children('tbody');
           var tbBodyTr = tbBody.find('tr');
           var sortIndex = -1;
           tbHeadTh.each(function()
           {
               var thisIndex = tbHeadTh.index($(this));
               $(this).mouseover(function()
               {
                   tbBodyTr.each(function()
                   {
                       var tds = $(this).find("td");
                       $(tds[thisIndex]).addClass("hover");
                   });
               }).mouseout(function()
               {
                    tbBodyTr.each(function()
                    {
                        var tds = $(this).find("td");
                        $(tds[thisIndex]).removeClass("hover");
                    });
                });
                $(this).click(function()
                {
                    var dataType = $(this).attr("type");
                    checkColumnValue(thisIndex, dataType);
                });
            });

            $("tbody tr").removeClass();
            $("tbody tr").mouseover(function()
            {
                $(this).addClass("hover");
            }).mouseout(function()
            {
                $(this).removeClass("hover");
            });

            function checkColumnValue(index, type) {
                var trsValue = new Array();
                tbBodyTr.each(function()
                {
                    var tds = $(this).find('td');
                    trsValue.push(type + ".separator" + $(tds[index]).html() + ".separator" + $(this).html());
                    $(this).html("");
                });
                var len = trsValue.length;
                if(index == sortIndex){
                    trsValue.reverse();
                }
                else
                {
                    for(var i = 0; i < len; i++){
                        type = trsValue[i].split(".separator")[0];
                        for(var j = i + 1; j < len; j++){
                            value1 = trsValue[i].split(".separator")[1];
                            value2 = trsValue[j].split(".separator")[1];
                            if(type == "number"){
                                value1 = value1 == "" ? 0 : value1;
                                value2 = value2 == "" ? 0 : value2;
                                if(parseFloat(value1) > parseFloat(value2))
                                {
                                    var temp = trsValue[j];
                                    trsValue[j] = trsValue[i];
                                    trsValue[i] = temp;
                                }
                            }
                            else
                            {
                                if (value1.localeCompare(value2) > 0)
                                {
                                    var temp = trsValue[j];
                                    trsValue[j] = trsValue[i];
                                    trsValue[i] = temp;
                                }
                            }
                        }
                    }
                }
                for(var i = 0; i < len; i++)
                {
                    $("tbody tr:eq(" + i + ")").html(trsValue[i].split(".separator")[2]);
                }
                sortIndex = index;
            }
            })
    </script>
</body>
</html>

admission/information/templates/adminsite/history_edit.html
  <h2>历史排名信息</h2>
  <p>省份：{{info.province}}</p>
  <p>专业：{{info.major}}</p>
  <p>文理科：{{info.major.sciorart}}</p>
  <form action="{% url 'adminsite:history_edit' info.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save</button>
  </form>

admission/information/templates/adminsite/history_info.html
<!DOCTYPE HTML>
<html>
  <head>
    <title> 统计信息 </title>
    <meta charset="utf-8">
    <meta name="Generator" content="EditPlus">
    <meta name="Author" content="tschengbin">
    <meta name="Keywords" content="jquery tableSort">
    <meta name="Description" content="">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <style type="text/css">
        p{
            width: 1024px;
            margin: 0 auto;
        }
        table{
            border: solid 1px #666;
            border-collapse: collapse;
            width: 100%;
            cursor: default;
            table-layout: fixed;
        }
        tr{
            border: solid 1px #666;
            height: 30px;
        }
        table thead tr{
            background-color: #ccc;
        }
        td{
            border: solid 1px #666;
            white-space:nowrap;
            overflow:hidden;
            text-overflow: ellipsis;
        }
        th{
            border: solid 1px #666;
            text-align: center;
            cursor: pointer;
        }
        .sequence{
            text-align: center;
        }
    </style>
  </head>

  <h2>考生统计信息</h2>
  <p>生源省份</p>
  <p>省份：{{province}}</p>
  </div>
  <table id="tableSort">
    <thead>
      <tr>
        <th type="number">ID</th>
        <th type="string">专业名称</th>
        <th type="number">历年录取排名</th>
        <th type="string">文理科</th>
        <th type="string">操作</th>
      </tr>
    </thead>
    <tbody>
    {% for data in datas %}
      <tr>
        <td>{{ data.id }}</td>
        <td >{{ data.major }}</td>
        <td>{{ data.rank }}</td>
        <td>{{ data.major.sciorart }}</td>
        <td> <a href="{% url 'adminsite:history_edit' data.id %}">{{ "修改" }}</a></td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <div>
  </div>
  <div>
    <p><a href="{% url 'information:index' %}">返回首页</a></p>
  </div>
  <script type="text/javascript">
      $(document).ready(function(){
           var tableObject = $('#tableSort');
           var tbHead = tableObject.children('thead');
           var tbHeadTh = tbHead.find('tr th');
           var tbBody = tableObject.children('tbody');
           var tbBodyTr = tbBody.find('tr');
           var sortIndex = -1;
           tbHeadTh.each(function()
           {
               var thisIndex = tbHeadTh.index($(this));
               $(this).mouseover(function()
               {
                   tbBodyTr.each(function()
                   {
                       var tds = $(this).find("td");
                       $(tds[thisIndex]).addClass("hover");
                   });
               }).mouseout(function()
               {
                    tbBodyTr.each(function()
                    {
                        var tds = $(this).find("td");
                        $(tds[thisIndex]).removeClass("hover");
                    });
                });
                $(this).click(function()
                {
                    var dataType = $(this).attr("type");
                    checkColumnValue(thisIndex, dataType);
                });
            });

            $("tbody tr").removeClass();
            $("tbody tr").mouseover(function()
            {
                $(this).addClass("hover");
            }).mouseout(function()
            {
                $(this).removeClass("hover");
            });

            function checkColumnValue(index, type) {
                var trsValue = new Array();
                tbBodyTr.each(function()
                {
                    var tds = $(this).find('td');
                    trsValue.push(type + ".separator" + $(tds[index]).html() + ".separator" + $(this).html());
                    $(this).html("");
                });
                var len = trsValue.length;
                if(index == sortIndex){
                    trsValue.reverse();
                }
                else
                {
                    for(var i = 0; i < len; i++){
                        type = trsValue[i].split(".separator")[0];
                        for(var j = i + 1; j < len; j++){
                            value1 = trsValue[i].split(".separator")[1];
                            value2 = trsValue[j].split(".separator")[1];
                            if(type == "number"){
                                value1 = value1 == "" ? 0 : value1;
                                value2 = value2 == "" ? 0 : value2;
                                if(parseFloat(value1) > parseFloat(value2))
                                {
                                    var temp = trsValue[j];
                                    trsValue[j] = trsValue[i];
                                    trsValue[i] = temp;
                                }
                            }
                            else
                            {
                                if (value1.localeCompare(value2) > 0)
                                {
                                    var temp = trsValue[j];
                                    trsValue[j] = trsValue[i];
                                    trsValue[i] = temp;
                                }
                            }
                        }
                    }
                }
                for(var i = 0; i < len; i++)
                {
                    $("tbody tr:eq(" + i + ")").html(trsValue[i].split(".separator")[2]);
                }
                sortIndex = index;
            }
            })
    </script>
</body>
</html>