admission/adminsite/urls.py
from django.urls import path
from . import views
app_name='adminsite'
urlpatterns=[
    path('history_info', views.history_info, name='history_info'),
    path('history_edit/<int:info_id>', views.history_edit, name='history_edit'),
    path('borderline_predict', views.borderline_predict, name='borderline_predict'),
]

admission/admission/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('information.urls',namespace='information')),
    path('users/',include('users.urls',namespace='users')),
    path('managesite/', include('managesite.urls',namespace='managesite')),
    path('adminsite/', include('adminsite.urls',namespace='adminsite')),
    path('material/', include('material.urls',namespace='material')),
]

admission/information/urls.py
from django.urls import path
from . import views

app_name='informations'

urlpatterns=[
    path('', views.index, name='index'),
    path('admin_index', views.admin_index, name='admin_index'),
    path('stu_menu', views.stu_menu, name='stu_menu'),
    path('new_stu/', views.new_stu, name='new_stu'),
    path('store_success/', views.store_success, name='store_success'),
    path('store_failed/', views.store_failed, name='store_failed'),
    path('exists/<int:info_id>/<int:info_testnum>', views.exists, name='exists'),
    path('search_info/', views.search_info, name='search_info'),
    path('edit_info/<int:info_id>/<int:info_testnum>', views.edit_info, name='edit_info'),
    path('admin_display', views.admin_display, name='admin_display'),
    path('admin_edit/<int:info_id>',views.admin_edit,name='admin_edit'),
    path('output/<int:province_id>',views.output,name='output'),
    path('rank_display/', views.rank_display, name='rank_display'),
    path('delete/<int:info_id>',views.delete, name='delete')
]

admission/managesite/urls.py
from django.urls import path
from . import views

app_name='managesite'

urlpatterns=[
    path('account_state/', views.account_state, name='account_state'),
    path('account_edit/<int:user_id>', views.account_edit, name='account_edit'),
    path('major_info/', views.major_info, name='major_info'),
    path('major_edit/<int:major_id>', views.major_edit, name='major_edit'),
    path('access_deny/', views.access_deny, name='access_deny'),
    path('new_major/', views.new_major, name='new_major'),
    path('delete/<int:info_id>', views.delete, name='delete'),
]

admission/material/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from admission.settings import MEDIA_ROOT
from django.views.static import serve
from . import views
app_name='material'

urlpatterns=[
    path('upload', views.upload, name='upload'),
    url(r'^file/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT},name='file'),
    path('file_display', views.file_display , name='file_display'),
    path('file_summary',views.file_summary, name='file_summary'),
    path('file_editname/<int:id>',views.file_editname, name='file_editname'),
    path('file_delete/<int:id>', views.file_delete, name='file_delete'),
    path('admin_file_display', views.admin_file_display , name='admin_file_display'),
]

admission/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from . import views
app_name='users'

urlpatterns=[
    path('register', views.register, name='register'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout',views.logout_view,name='logout'),
    path('place',views.place,name='place'),
    path('admin_place',views.admin_place,name='admin_place'),
]

admission/information/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class MajorInfo(models.Model):
    major_name = models.CharField(max_length=30)
    sciorart = models.ForeignKey('SciorArt', on_delete=models.CASCADE)
    is_international=models.BooleanField()
    def __str__(self):
        return self.major_name
class SciorArt(models.Model):
    SciorArt=models.CharField(max_length=2)
    def __str__(self):
        return self.SciorArt

class StuInfo(models.Model):
    id = models.AutoField(primary_key=True)                         #自增的id，作为主键
    name = models.CharField(max_length=20)                          #姓名
    testnum = models.CharField(max_length=14)                       #考生号，通常最多14位
    score = models.PositiveSmallIntegerField()                      #小整数，存储最大32767
    rank = models.PositiveSmallIntegerField()                       #排名，目前可存储最大32767
    tele = models.CharField(max_length=20)                          #电话
    high_school = models.CharField(max_length=30)                   #毕业学校
    sciorart = models.ForeignKey('SciorArt',on_delete=models.CASCADE)
    major1 = models.ForeignKey('MajorInfo',on_delete=models.CASCADE,related_name='major1')
    major2 = models.ForeignKey('MajorInfo', on_delete=models.CASCADE,null=True,blank=True,related_name='major2')
    major3 = models.ForeignKey('MajorInfo', on_delete=models.CASCADE,null=True,blank=True,related_name='major3')
    is_international = models.BooleanField(default=False)
    application_rank = models.PositiveSmallIntegerField()
    staff = models.ForeignKey(User,on_delete=models.CASCADE,null=True,)     #自动生成，无需填写
    province = models.ForeignKey('users.Province',null=True,on_delete=models.CASCADE)
    place = models.CharField(max_length=30,default="NULL")        #自动生成，无需填写
    tip = models.CharField(max_length=200,null=True,blank=True)   #由后台管理员填写
    date = models.DateField(auto_now_add=True)
    time  = models.TimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural ='entries'


class RankPredict(models.Model):
    province = models.ForeignKey('users.Province',on_delete=models.CASCADE)
    sciorart = models.ForeignKey('SciorArt', on_delete=models.CASCADE,default=1)
    score = models.PositiveSmallIntegerField()
    highrank = models.PositiveSmallIntegerField(null=True,blank=True)
    lowrank = models.PositiveSmallIntegerField(null=True,blank=True)

admission/information/forms.py
from django import forms
from .models import StuInfo


class StuInfoForms(forms.ModelForm):
    class Meta:
        model=StuInfo
        fields=['name','testnum','score','rank','tele','high_school','sciorart','major1','major2','major3','application_rank']
        labels={'name':'姓名','testnum':'考号','score':'分数','rank':'排名','tele':'电话','high_school':'毕业中学','sciorart':'文科/理科','major1':'第一意向专业','major2':'第二意向专业（选填）','major3':'第三意向专业（选填）','application_rank':'第几志愿'}


class SearchForms(forms.ModelForm):
    class Meta:
        model = StuInfo
        fields = ['name', 'testnum']
        labels = {'name': '姓名', 'testnum': '考号'}

class AdminEditForms(forms.ModelForm):
    class Meta:
        model=StuInfo
        fields=['name','testnum','score','rank','tele','high_school','sciorart','major1','major2','major3','is_international','application_rank','place','tip']
        labels={'name':'姓名','testnum':'考号','score':'分数','rank':'排名','tele':'电话','high_school':'毕业中学','sciorart':'文科/理科','major1':'第一意向专业','major2':'第二意向专业','major3':'第三意向专业','is_international':'是否报考国际学院','application_rank':'第几志愿','place':'地点','tip':'备注'}
        widgets = {'tip': forms.Textarea(attrs={'cols': 80})}

admission/information/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from django.urls import resolve
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .models import StuInfo,RankPredict
from .forms import StuInfoForms,SearchForms,AdminEditForms
from users.models import UserProfile, Province
from material.models import ConsultMaterial
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import render,HttpResponse
import xlwt
from . import models

from io import StringIO,BytesIO

@login_required
def admin_index(request):
    if request.user.is_superuser is True or request.user.is_staff is True:
        return render(request, 'information/admin_index.html')
    else:
        raise Http404

@login_required
def index(request):
    if request.user.is_superuser is True or request.user.is_staff is True:
        return admin_index(request)
    else:
        user_province_id = UserProfile.objects.get(user=request.user).province.id
        file = ConsultMaterial.objects.filter(province_id__in=[user_province_id, 0])[:2]
        tele = UserProfile.objects.get(user=request.user).telephone
        print(tele)
        context = {'file': file, 'tele':tele, 'name':request.user.first_name}
        return render(request,'information/index.html', context)

def stu_menu(request):
    return render(request,'information/stu_menu.html')

def store_success(request):
    return render(request, 'information/store_success.html')

def store_failed(request):
    return render(request, 'information/store_failed.html')

def exists(request,info_id ,info_testnum):
    context = {'info_id': info_id, 'info_testnum': info_testnum}
    return render(request, 'information/exists.html',context)

def update_predict(new_info):
    try:
        data = RankPredict.objects.get(score=new_info.score,province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        if data.highrank > new_info.rank or data.highrank is 0:
            data.highrank = new_info.rank
        if data.lowrank < new_info.rank or data.lowrank is 0:
            data.lowrank = new_info.rank
    except RankPredict.DoesNotExist:
        models.RankPredict.objects.create(score=new_info.score,province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        data = RankPredict.objects.get(score=new_info.score, province_id=new_info.province_id,sciorart_id=new_info.sciorart_id)
        data.highrank= new_info.rank
        data.lowrank = new_info.rank
    data.save()
def dupcheck(request,form):
    data = form.cleaned_data
    curnum = data['testnum']
    curname = data['name']
    try:
        dup = StuInfo.objects.get(name=curname, testnum=curnum)
    except StuInfo.DoesNotExist:
        dup = None
    if dup is None:
        new_info=form.save(commit=False)
        cur= request.user
        new_info.staff = cur
        curprofile = UserProfile.objects.get(user=cur)
        new_info.province=curprofile.province
        new_info.place=curprofile.place
        if new_info.major1.is_international is 1:
            new_info.is_international=True
        if new_info.major2:
            if new_info.major2.is_international is 1:
                new_info.is_international=True
        if new_info.major3:
            if new_info.major3.is_international is 1:
                new_info.is_international=True
        update_predict(new_info)
        new_info.save()
        return HttpResponseRedirect(reverse('information:store_success'))
    else:
        return HttpResponseRedirect(reverse('information:exists', kwargs={"info_id":dup.id,"info_testnum":dup.testnum}))

@login_required
def new_stu(request):
    if request.method!='POST':
        form=StuInfoForms()
    else:
        form=StuInfoForms(request.POST)
        if form.is_valid():
            return dupcheck(request,form)

    context={'form':form}
    return render(request, 'information/new_stu.html', context)

@login_required
def search_info(request):
    if request.method!='POST':
        form=SearchForms()
    else:
        form=SearchForms(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            curnum = data['testnum']
            curname = data['name']
            try:
                dup = StuInfo.objects.get(name=curname, testnum=curnum)
            except StuInfo.DoesNotExist:
                dup = None
            if dup is None:
                return HttpResponseRedirect(reverse('information:store_failed'))
            else:
                return HttpResponseRedirect(reverse('information:edit_info', kwargs={"info_id":dup.id,"info_testnum":dup.testnum}))
    context={'form':form}
    return render(request, 'information/search_info.html', context)

@login_required
def edit_info(request,info_id ,info_testnum):
    try:
        info=StuInfo.objects.get(id=info_id,testnum=info_testnum)
    except StuInfo.DoesNotExist:
        raise Http404
    if request.method!='POST':
        form=StuInfoForms(instance=info)
    else:
        form=StuInfoForms(instance=info,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('information:store_success'))

    context = {'info':info,'form': form}
    return render(request, 'information/edit_info.html', context)

def admin_only(request):
    if request.user.is_staff is False:
        raise Http404

@login_required
def admin_display(request):
    admin_only(request)
    data = []
    provinces= Province.objects.all()
    curprofile = UserProfile.objects.get(user=request.user)
    default = curprofile.province
    if not default:
        default = 1
    province_id = request.GET.get('province','')
    if province_id:
        data = StuInfo.objects.filter(province=province_id)
    else:
        data = StuInfo.objects.filter(province=default)
        province_id = default.id

    context={'datas': data,'cur_province':province_id, 'provinces': provinces, 'default': default}
    return render(request,'information/admin_display.html',context)

@login_required
def admin_edit(request,info_id):
    info = StuInfo.objects.get(id=info_id)
    if request.method != 'POST':
        form = AdminEditForms(instance=info)
    else:
        form = AdminEditForms(instance=info, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('information:admin_display'))

    context = {'info': info, 'form': form}
    return render(request, 'information/admin_edit.html', context)


@login_required
def output(request,province_id):
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment;filename=information.xls'
    wb = xlwt.Workbook(encoding = 'utf-8')
    sheet = wb.add_sheet(u'考生信息')
    #1st line
    sheet.write(0,0, '编号')
    sheet.write(0,1, '姓名')
    sheet.write(0,2, '考号')
    sheet.write(0,3, '成绩')
    sheet.write(0,4, '排名')
    sheet.write(0,5, '电话')
    sheet.write(0,6, '毕业高中')
    sheet.write(0,7, '文理科')
    sheet.write(0, 8, '第一意向专业')
    sheet.write(0, 9,'第二意向专业')
    sheet.write(0, 10, '第三意向专业')
    sheet.write(0, 11, '是否填报国际学院')
    sheet.write(0, 12, '第几志愿')
    sheet.write(0, 13, '省份')
    sheet.write(0, 14, '录入教师')
    sheet.write(0, 15, '咨询点')
    sheet.write(0, 16, '备注')
    sheet.write(0, 17, '录入日期')
    sheet.write(0, 18, '录入时间')
    row=1
    for info in StuInfo.objects.filter(province=province_id):
        sheet.write(row, 0, info.id)
        sheet.write(row, 1, info.name)
        sheet.write(row, 2, info.testnum)
        sheet.write(row, 3, info.score)
        sheet.write(row, 4, info.rank)
        sheet.write(row, 5, info.tele)
        sheet.write(row, 6, info.high_school)
        sheet.write(row, 7, str(info.sciorart))
        sheet.write(row, 8, str(info.major1))
        sheet.write(row, 9, str(info.major2))
        sheet.write(row, 10, str(info.major3))
        sheet.write(row, 11, str(info.is_international))
        sheet.write(row, 12, info.application_rank)
        sheet.write(row, 13, str(info.province))
        sheet.write(row, 14, info.staff.first_name)
        sheet.write(row, 15, info.place)
        sheet.write(row, 16, info.tip)
        sheet.write(row, 17, str(info.date))
        sheet.write(row, 18, str(info.time))
        row = row + 1
    output = BytesIO()
    wb.save(output)
    output.seek(0)
    response.write(output.getvalue())
    return response

def rank_display(request):
    admin_only(request)
    provinces= Province.objects.all()
    curprofile = UserProfile.objects.get(user=request.user)
    default = curprofile.province
    province_id = request.GET.get('province','')
    if not province_id:
        province_id=default
    datas=RankPredict.objects.filter(province=province_id)
    for data in datas:
        data.delete()
    datas=StuInfo.objects.filter(province=province_id)
    for data in datas:
        update_predict(data)
    scidata = []
    artdata = []
    if province_id:
        scidata = RankPredict.objects.filter(province=province_id,sciorart=1).order_by('-score')
        artdata = RankPredict.objects.filter(province=province_id, sciorart=2).order_by('-score')
    if len(scidata) > 0:
        cur=scidata[0].score
        for data in scidata:
            while data.score != cur:
                models.RankPredict.objects.create(score=cur,province=data.province,sciorart=data.sciorart,highrank=0,lowrank=0)
                cur=cur-1
            cur=cur-1
    if len(artdata) > 0:
        cur=artdata[0].score
        for data in artdata:
            while data.score is not cur:
                models.RankPredict.objects.create(score=cur,province=data.province,sciorart=data.sciorart,highrank=0,lowrank=0)
                cur = cur - 1
            cur = cur - 1

admission/information/templates/information/admin_edit.html
  <h2>修改考生信息</h2>

  <form action="{% url 'information:admin_edit' info.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save</button>
  </form>

admission/information/templates/information/admin_index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0046)https://zsb.bupt.edu.cn/list/list.php?p=10_8_1 -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load static %}
<link href="{% static "common.css" %}" rel="stylesheet" type="text/css">
	{% load static %}
<script src="{% static "hm.js.下载" %}"></script>
    {% load static %}
<script src="{% static "jquery-1.7.2.js.下载" %}" type="text/javascript" > </script>
	{% load static %}
<script type="text/javascript" src="{% static "jquery.sgallery.js.下载" %}"></script>
	{% load static %}
<script src="{% static "js.js.下载" %}" type="text/javascript"></script>
<title>北京邮电大学招生宣传系统</title>
</head>

<body>
<div class="head">
<div class="header grd25 mar0a">
		{% load static %}
	<div class="logo lf"><a href="{% url 'information:index' %}"><img src="{% static "zslogo.jpg" %}"" alt="北京邮电大学本科生招生网"></a></div>
	<div class="top_right rt">
    <ul class="h30 rt padtb10">
		<p style="color:#fff;height:27px;">
			{% if user.is_authenticated %}
		    您好,{{ user.username }}.
              <a class="top_nav" href="{% url 'users:logout' %}">注销</a>
			{% else %}
              <a class="top_nav" href="{% url 'users:register' %}">注册</a> ----
              <a class="top_nav" href="{% url 'users:login' %}">登陆</a>
             {% endif %}
		</p>
	</ul>
		<div class="bk20"></div>
	</div>
	<div class="nav rt" id="top_nav">
		<ul>
					<li><a class="top_nav" id="nav_on" href="{% url 'information:index' %}">首页</a>
					    </li>
			        <li><a class="top_nav" href="{% url 'users:place' %}" target="_self">个人信息修改</a>
					    </li>

					<li><a class="top_nav" href="{% url 'information:admin_display' %}" target="_self">考生信息汇总</a>
						</li>
					<li><a class="top_nav" href="{% url 'adminsite:history_info' %}" target="_self">历史排名录入</a>
						</li>
			        <li><a class="top_nav" href="{% url 'information:index' %}" target="_self">系统预测信息</a>
						<dl>
							<dd><a href="{% url 'information:rank_display' %}" target="_self">分数排名关系预估</a></dd>
							<dd><a href="{% url 'adminsite:borderline_predict' %}" target="_self">录取分数线预估</a></dd>
						</dl>
					</li>
			        <li><a class="top_nav" href="{% url 'information:index' %}" target="_self">招生资料管理</a>
						<dl>
							<dd><a href="{% url 'material:file_display' %}" target="_self">本省招生资料展示</a></dd>
							<dd><a href="{% url 'material:upload' %}" target="_self">招生资料上传</a></dd>
							<dd><a href="{% url 'material:file_summary' %}" target="_self">招生资料管理</a></dd>
						</dl>
					</li>
			        <li><a class="top_nav" href="{% url 'information:index' %}" target="_self">网站管理</a>
						<dl>
							<dd><a href="{% url 'managesite:account_state' %}" target="_self">账号权限管理</a></dd>
							<dd><a href="{% url 'managesite:major_info' %}" target="_self">专业信息管理</a></dd>
						</dl>
					</li>
				</ul>
	</div>


<div class="bk"></div>
</div> <!--/header-->
</div> <!--/header--><div class="wrap">
<div class="mar0a grd25">
	<div class="bk10"></div>
		{% load static %}
	<div id="mid-pic" ><img width="1000" height="150" src="{% static "banner.jpg" %}"></div>
<div class="bk10"></div>
<div class="grd25">

<div class="lf">
	<div class="bk10"></div>
	<div class="lf wrap_com grd9 padb10 ovhi marr20">
		<div class="title h30 lh30 padl10 marl10"><h2 class="lf"><a href="{% url 'information:admin_display' %}">收集信息汇总</a></h2></div>
		<div class="bk"></div>
	</div>

	<div class="lf grd9 wrap_com padb10">
		<div class="title h30 lh30 padl10 marr10"><h2 class="lf"><a href="{% url 'adminsite:history_info' %}" >历史录取信息录入</a></h2></div>
		<br></br>
		<div class="bk"></div>
	</div>


<div class="bk"></div>

	<div class="lf grd9 wrap_com padb10">
		<div class="title h30 lh30 padl10 marl10"><h2 class="lf">系统预测信息</h2></div>
		<div class="bk"></div>
		<ul class="padlr10">
					 <li><a class="lh28 h28 " href="{% url 'information:rank_display' %}">•&nbsp;排名分数关系预测</a></li>
			         <li><a class="lh28 h28 " href="{% url 'adminsite:borderline_predict' %}">•&nbsp;录取分数线预测</a></li>
				</ul>
	</div>
	<div class="rt grd9 wrap_com padb10">
		<div class="title h30 lh30 padl10"><h2 class="lf">招生资料管理</h2></div>
		<div class="bk"></div>
		<ul class="padlr10">
					 <li><a class="lh28 h28 " href="{% url 'material:file_display' %}">•&nbsp;本省招生资料查看</a></li>
					 <li><a class="lh28 h28 " href="{% url 'material:upload' %}" target="_self">•&nbsp;招生资料上传</a></li>
					 <li><a class="lh28 h28 " href="{% url 'material:file_summary' %}">•&nbsp;招生资料名称修改和删除</a></li>
				</ul>
	</div>
<div class="bk10"></div>
	<div class="lf grd9 wrap_com padb10">
		<div class="title h30 lh30 padl10 marl10"><h2 class="lf">网站账号管理</h2></div>
		<div class="bk"></div>
		<ul class="padlr10">
					 <li><a class="lh28 h28" href="{% url 'managesite:account_state' %}">•&nbsp;网站账号信息管理</a></li>
					 <li><a class="lh28 h28" href="{% url 'managesite:major_info' %}">•&nbsp;招生专业信息管理</a></li>
				</ul>
	</div>
	<div class="bk"></div>
</div>


</div>
</div>
</div>
<div class="bk10"></div>
</div>
<div class="bk"></div>
</div>
<div class="bk10"></div>
</div><!--/wrap-->


</div>
</body></html>

admission/information/templates/information/base.html
<p>
<h1><a href="{% url 'information:index' %}">北京邮电大学招生咨询平台</a></h1>
  {% if user.is_authenticated %}
    您好,{{ user.username }}.
    <a href="{% url 'users:logout' %}">注销</a>
  {% else %}
  <a href="{% url 'users:register' %}">注册</a>--
  <a href="{% url 'users:login' %}">登陆</a>
  {% endif %}
</p>

<p>全站信息管理:
  <a href="{% url 'managesite:account_state' %}">账号权限管理</a>---
  <a href="{% url 'managesite:major_info' %}">专业信息管理</a>--
  <a href="{% url 'material:upload' %}">上传招生宣传材料</a>--
  <a href="{% url 'material:file_summary' %}">查看招生宣传材料</a>
</p>
<p>本省信息管理功能：
  <a href="{% url 'material:upload' %}">上传招生宣传材料</a>--
  <a href="{% url 'material:file_summary' %}">修改本省招生宣传材料</a>--
    <a href="{% url 'material:file_display' %}">查看招生宣传材料</a>--
  <a href="{% url 'information:admin_display' %}">收集信息汇总</a>---
  <a href="{% url 'information:rank_display' %}">排名与分数关系预估</a>---
  <a href="{% url 'adminsite:history_info' %}">历史录取排名录入</a>---
  <a href="{% url 'adminsite:borderline_predict' %}">本年录取分数线预测</a>
</p>

<p> 展示收集修改信息:
  <a href="{% url 'material:file_display' %}">查看招生宣传材料</a>--
  <a href="{% url 'information:index' %}">考生信息录入/更改</a>---
  <a href="{% url 'users:place' %}">咨询地点更改</a>
</p>
<div>-----------------------------------------------------------------------------------------------------------------</div>
<div></div>
{% block content %}
{% endblock content %}

admission/information/templates/information/new_major.html
  <h2>新增专业信息</h2>
  <form action="{% url 'managesite:new_major'%}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save</button>
  </form>